import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Canvas,useFrame} from '@react-three/fiber';
import {Float,Environment,ContactShadows} from '@react-three/drei';
import gsap from 'gsap';
import {ScrollTrigger} from 'gsap/ScrollTrigger';
import Lenis from 'lenis';
import './styles.css';

gsap.registerPlugin(ScrollTrigger);
const FORM='https://docs.google.com/forms/d/e/1FAIpQLSdba2qlmHLW7gPMyTsub61LjWstbIYDMooEuv6m0m5DNpngSA/viewform?pli=1';
const proteins=[['Chicken',113.75],['Tilapia',120.25],['Ground Beef',126.75],['Steak Cut',152.75],['Salmon',65]];
const vegetables=['Green Beans','Broccoli','Cabbage','Collard Greens','Mixed Vegetables','Seasoned Corn','Roasted Brussels Sprouts','Glazed Carrots','Sautéed Spinach','Candied Yams'];
const sides=['Mac & Cheese','Rice & Peas','Plantains','Sweet Potatoes','Roasted Potatoes','Quinoa'];
const desserts=['Cinnamon Rolls: Regular','Cinnamon Rolls: Pumpkin','Cake: 1 slice — $5','Cake: 2 slices — $10','Cake: 3 slices — $15','Cake: 4 slices — $20','Cake: 5 slices — $25'];
function FoodOrb(){const ref=useRef();useFrame(s=>{if(!ref.current)return;ref.current.rotation.y=s.clock.elapsedTime*.22;ref.current.rotation.x=Math.sin(s.clock.elapsedTime*.7)*.08});return <Float speed={1.4} rotationIntensity={.35} floatIntensity={.8}><group ref={ref}><mesh position={[0,-.15,0]}><cylinderGeometry args={[1.55,.95,.32,64]}/><meshStandardMaterial color="#e8c8c0" metalness={.12} roughness={.24}/></mesh><mesh position={[0,.08,0]}><sphereGeometry args={[1.18,64,32]}/><meshStandardMaterial color="#d98e80" roughness={.32}/></mesh><mesh position={[0,.48,.05]} scale={[1.05,.24,1.05]}><sphereGeometry args={[1,48,24]}/><meshStandardMaterial color="#f4e8d7" roughness={.38}/></mesh><mesh position={[-.42,.48,.42]} scale={.18}><sphereGeometry args={[1,24,16]}/><meshStandardMaterial color="#7b9b68"/></mesh><mesh position={[.38,.5,.3]} scale={.16}><sphereGeometry args={[1,24,16]}/><meshStandardMaterial color="#b36c58"/></mesh></group></Float>}
function Scene(){return <div className="scene"><Canvas camera={{position:[0,0,5],fov:38}} dpr={[1,1.5]}><ambientLight intensity={2.2}/><directionalLight position={[3,4,4]} intensity={3}/><pointLight position={[-3,1,2]} intensity={2} color="#f4b8ad"/><FoodOrb/><ContactShadows position={[0,-1.25,0]} opacity={.2} scale={5} blur={2.5}/><Environment preset="studio"/></Canvas></div>}
function App(){
 const [protein,setProtein]=useState('Chicken'),[pan,setPan]=useState('small'),[qty,setQty]=useState(1),[veg,setVeg]=useState('Green Beans'),[side,setSide]=useState('Mac & Cheese'),[extra,setExtra]=useState('None'),[dessert,setDessert]=useState('None');
 const base=proteins.find(x=>x[0]===protein)?.[1]||0; const panAdj=pan==='large'?base*.855:base; const vegCost=pan==='large'?60:35; const sideCost=pan==='large'?60:30; const extraCost=extra==='Additional Vegetable'?(pan==='large'?39:22.75):extra==='Additional Starch/Side'?(pan==='large'?39:22.75):0; const dessertCost=dessert.startsWith('Cake:')?Number(dessert.match(/\$(\d+)/)?.[1]||0):0; const total=(panAdj+vegCost+sideCost+extraCost+dessertCost)*qty;
 useEffect(()=>{const lenis=new Lenis({duration:1.1,smoothWheel:true});function raf(t){lenis.raf(t);requestAnimationFrame(raf)}requestAnimationFrame(raf);const ctx=gsap.context(()=>{gsap.utils.toArray('.reveal').forEach(el=>gsap.fromTo(el,{y:50,opacity:0},{y:0,opacity:1,duration:1,ease:'power3.out',scrollTrigger:{trigger:el,start:'top 85%'}}));});return()=>{ctx.revert();lenis.destroy()};},[]);
 return <><div className="grain"/><header><a className="brand" href="#top">Sincerely <i>Serenity</i></a><nav><a href="#menu">Menu</a><a href="#story">Our Table</a><a href="#quote">Build a Pan</a></nav><a className="navCta" href={FORM} target="_blank" rel="noreferrer">Order Catering</a></header><main id="top">
 <section className="hero"><div className="heroCopy reveal"><p className="eyebrow">CATERING • MADE WITH CARE</p><h1>Food that feels like <em>home,</em> elevated.</h1><p className="lead">Beautiful pans, generous portions, and soulful comfort food for the moments worth gathering around.</p><div className="actions"><a className="button primary" href="#quote">Build your order</a><a className="button ghost" href="#menu">Explore the menu</a></div><div className="micro"><span>Mon–Thu</span> 6:00 AM–8:00 PM <b>•</b> Orders require 1 day notice</div></div><Scene/><div className="heroBadge">SINCERELY<br/><span>SERENITY</span></div></section>
 <section className="marquee"><div>COMFORT • CELEBRATION • CATERING • GATHER WELL • COMFORT • CELEBRATION • CATERING •</div></section>
 <section id="menu" className="section menu"><div className="sectionHead reveal"><p className="eyebrow">THE MENU</p><h2>Made for the whole table.</h2><p>Each pan includes one protein, one vegetable, and one starch/side. Add extras when your gathering calls for more.</p></div><div className="cards">{proteins.map(([name,price],i)=><article className="foodCard reveal" key={name}><span className="num">0{i+1}</span><div className="miniPlate"><span className="foodShape"/></div><h3>{name}</h3><p>{name==='Chicken'?'Tender, familiar, and always welcome.':name==='Tilapia'?'Light, seasoned, and celebration-ready.':name==='Ground Beef'?'Rich comfort for a hungry table.':name==='Steak Cut'?'The elevated choice for a special spread.':'A premium favorite for seafood lovers.'}</p><strong>Small pan from ${price.toFixed(2)}</strong></article>)}</div></section>
 <section id="story" className="story"><div className="storyShape"/><div className="storyCopy reveal"><p className="eyebrow">OUR TABLE</p><h2>There is something powerful about a full table.</h2><p>Sincerely Serenity is built around the feeling that good food should slow the room down. From family celebrations to office gatherings, we make the meal one less thing you have to worry about.</p><div className="statRow"><div><b>8–12</b><span>small-pan servings</span></div><div><b>15–25</b><span>large-pan servings</span></div><div><b>1 day</b><span>minimum notice</span></div></div></div></section>
 <section id="quote" className="section quote"><div className="sectionHead reveal"><p className="eyebrow">BUILD YOUR SPREAD</p><h2>A little taste of your final quote.</h2><p>Use this estimator to explore your options. Your final price is confirmed after Sincerely Serenity reviews the request.</p></div><div className="quoteGrid reveal"><div className="controls"><label>Pan size<select value={pan} onChange={e=>setPan(e.target.value)}><option value="small">9×13 Small • 8–12 servings</option><option value="large">19×11 Large • 15–25 servings</option></select></label><label>Protein<select value={protein} onChange={e=>setProtein(e.target.value)}>{proteins.map(([x])=><option key={x}>{x}</option>)}</select></label><label>Vegetable<select value={veg} onChange={e=>setVeg(e.target.value)}>{vegetables.map(x=><option key={x}>{x}</option>)}</select></label><label>Starch / side<select value={side} onChange={e=>setSide(e.target.value)}>{sides.map(x=><option key={x}>{x}</option>)}</select></label><label>Additional item<select value={extra} onChange={e=>setExtra(e.target.value)}><option>None</option><option>Additional Vegetable</option><option>Additional Starch/Side</option></select></label><label>Dessert<select value={dessert} onChange={e=>setDessert(e.target.value)}><option>None</option>{desserts.map(x=><option key={x}>{x}</option>)}</select></label><label>Number of pans<input type="number" min="1" max="20" value={qty} onChange={e=>setQty(Math.max(1,Math.min(20,Number(e.target.value)||1)))}/></label></div><aside className="receipt"><p>YOUR ESTIMATE</p><div className="receiptLine"><span>{qty} × {pan==='small'?'SMALL':'LARGE'} PAN</span><b>${(panAdj*qty).toFixed(2)}</b></div><div className="receiptLine"><span>{veg}</span><b>${(vegCost*qty).toFixed(2)}</b></div><div className="receiptLine"><span>{side}</span><b>${(sideCost*qty).toFixed(2)}</b></div>{extra!=='None'&&<div className="receiptLine"><span>{extra}</span><b>${(extraCost*qty).toFixed(2)}</b></div>}{dessert!=='None'&&<div className="receiptLine"><span>{dessert}</span><b>${(dessertCost*qty).toFixed(2)}</b></div>}<div className="total"><span>Starting estimate</span><strong>${total.toFixed(2)}</strong></div><small>Delivery, special requests, quantity changes and final selections may change the total. A $50 deposit is non-refundable under the no-show policy.</small><a className="button primary full" href={FORM} target="_blank" rel="noreferrer">Continue to catering form</a></aside></div></section>
 <section className="final"><p className="eyebrow">READY WHEN YOU ARE</p><h2>Let us feed your people beautifully.</h2><a className="button light" href={FORM} target="_blank" rel="noreferrer">Request your catering order</a><p>Questions or special meals? <a href="mailto:Aaleeyahx219@gmail.com">Aaleeyahx219@gmail.com</a></p></section></main><footer><div><strong>Sincerely Serenity</strong><span>Elevated comfort food • Catering with care</span></div><div><span>PayPal: Yahaziel05@gmail.com</span><span>Zelle: 352-454-5192</span></div></footer></>}
createRoot(document.getElementById('root')).render(<App/>);
